# fly.toml app configuration file generated for hacker-directory on 2026-01-15T22:10:16-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hacker-directory'
primary_region = 'iad'

[build]

[env]
PORT = '8080'

[processes]
app = 'run -A ./main.ts'

[http_service]
auto_start_machines = true
auto_stop_machines = 'stop'
force_https = true
internal_port = 8000
min_machines_running = 0
processes = ['app']

[[vm]]
cpus = 1
memory = '1gb'
memory_mb = 1024
